# HAR TFM

In [1]:
import pandas as pd
import numpy as np
import json

import math

import seaborn as sns
import matplotlib.pyplot as plt
sns.set(color_codes=True)
%matplotlib inline

from sklearn import metrics

ruta_archivo_csv = "Datos Combinados/data/DatosCombinados_Total.csv"

df = pd.read_csv(ruta_archivo_csv)
print(df)

              Ax  counter          deviceId         Mz         My   Bpressure  \
0      -0.158082        0  d99f0327fa491f9f  -5.456250 -45.337502  915.505005
1      -0.077317        1  d99f0327fa491f9f        NaN        NaN  915.512451
2      -0.004362        0  d99f0327fa491f9f  -9.018750 -45.900002  915.538757
3       0.050783        1  d99f0327fa491f9f -12.018750 -45.712502  915.567505
4       0.053467        2  d99f0327fa491f9f -12.825001 -45.393753  915.552490
...          ...      ...               ...        ...        ...         ...
309703       NaN        4   TP1A.220624.014        NaN        NaN         NaN
309704       NaN        2   TP1A.220624.014        NaN        NaN         NaN
309705       NaN        3   TP1A.220624.014        NaN        NaN         NaN
309706       NaN        4   TP1A.220624.014        NaN        NaN         NaN
309707       NaN        5   TP1A.220624.014        NaN        NaN         NaN

              Gy        Ay        Az       Mx  activity        Gz  \
0      -0.340853  0.531950  0.775127  0.56250         1  0.260450
1      -0.480737  0.495350  0.954223      NaN         1 -0.362767
2      -0.496084  0.585874  0.820999 -0.90000         1 -0.428662
3      -0.291909  0.535123  0.966667 -0.20625         1 -0.541592
4      -0.090405  0.418979  0.834419  0.78750         1 -0.430266
...          ...       ...       ...      ...       ...       ...
309703       NaN       NaN       NaN      NaN         6       NaN
309704       NaN       NaN       NaN      NaN         6       NaN
309705       NaN       NaN       NaN      NaN         6       NaN
309706       NaN       NaN       NaN      NaN         6       NaN
309707       NaN       NaN       NaN      NaN         6       NaN

                  timestamp  Lilluminance        Gx
0       2023-06-11 09:54:24       19857.0 -0.111403
1       2023-06-11 09:54:24           NaN -0.521053
2       2023-06-11 09:54:25           NaN -0.099644
3       2023-06-11 09:54:25           NaN -0.148436
4       2023-06-11 09:54:25           NaN -0.027564
...                     ...           ...       ...
309703  2023-12-04 20:09:39         101.0       NaN
309704  2023-12-04 20:09:40         102.0       NaN
309705  2023-12-04 20:09:40         103.0       NaN
309706  2023-12-04 20:09:40         101.0       NaN
309707  2023-12-04 20:09:40         100.0       NaN

[309708 rows x 15 columns]

/opt/Anaconda/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309708 entries, 0 to 309707
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Ax            307513 non-null  float64
 1   counter       309708 non-null  int64
 2   deviceId      178574 non-null  object
 3   Mz            272095 non-null  float64
 4   My            272095 non-null  float64
 5   Bpressure     6552 non-null    float64
 6   Gy            303103 non-null  float64
 7   Ay            307513 non-null  float64
 8   Az            307513 non-null  float64
 9   Mx            272095 non-null  float64
 10  activity      309708 non-null  int64
 11  Gz            303103 non-null  float64
 12  timestamp     309672 non-null  object
 13  Lilluminance  23581 non-null   float64
 14  Gx            303103 non-null  float64
dtypes: float64(11), int64(2), object(2)
memory usage: 35.4+ MB

## Reorganizar las columnas del csv.

In [3]:
columnas_deseadas = ["Ax", "Ay", "Az", "Gx", "Gy", "Gz", "Mx", "My", "Mz", "Bpressure", "Lilluminance", "timestamp", "counter","deviceId", "activity"]  # Cambia los nombres de las columnas según tus necesidades
df = df.reindex(columns=columnas_deseadas)

## Ordenar los datos.

In [4]:
df.head()

,Ax,Ay,Az,Gx,Gy,Gz,Mx,My,Mz,Bpressure,Lilluminance,timestamp,counter,deviceId,activity
0,-0.158082,0.531950,0.775127,-0.111403,-0.340853,0.260450,0.56250,-45.337502,-5.456250,915.505005,19857.0,2023-06-11 09:54:24,0,d99f0327fa491f9f,1
1,-0.077317,0.495350,0.954223,-0.521053,-0.480737,-0.362767,NaN,NaN,NaN,915.512451,NaN,2023-06-11 09:54:24,1,d99f0327fa491f9f,1
2,-0.004362,0.585874,0.820999,-0.099644,-0.496084,-0.428662,-0.90000,-45.900002,-9.018750,915.538757,NaN,2023-06-11 09:54:25,0,d99f0327fa491f9f,1
3,0.050783,0.535123,0.966667,-0.148436,-0.291909,-0.541592,-0.20625,-45.712502,-12.018750,915.567505,NaN,2023-06-11 09:54:25,1,d99f0327fa491f9f,1
4,0.053467,0.418979,0.834419,-0.027564,-0.090405,-0.430266,0.78750,-45.393753,-12.825001,915.552490,NaN,2023-06-11 09:54:25,2,d99f0327fa491f9f,1

In [5]:
df = df.sort_values(by=["timestamp", "counter"])
df.head(40)

,Ax,Ay,Az,Gx,Gy,Gz,Mx,My,Mz,Bpressure,Lilluminance,timestamp,counter,deviceId,activity
306278,-0.097234,0.418460,0.843996,0.286335,0.070782,0.084450,-1.368750,8.156250,-24.168751,NaN,NaN,2023-06-04 17:36:20,0,8fe3a65e2ea6658d,5
306279,0.249002,0.293410,1.201944,-0.177069,0.058947,0.357040,-1.443750,8.193750,-24.300001,NaN,NaN,2023-06-04 17:36:20,1,8fe3a65e2ea6658d,5
306280,0.240584,0.380152,1.015406,-0.172335,1.051955,0.423623,0.131250,8.212501,-23.943750,NaN,NaN,2023-06-04 17:36:21,0,8fe3a65e2ea6658d,5
306281,0.113704,0.335500,0.834236,-0.159355,0.307867,0.560376,1.837500,8.400001,-23.400002,NaN,NaN,2023-06-04 17:36:21,1,8fe3a65e2ea6658d,5
306282,0.038308,0.284992,0.928786,0.300766,0.246171,0.454623,3.618750,8.100000,-23.025002,NaN,NaN,2023-06-04 17:36:21,2,8fe3a65e2ea6658d,5
306283,-0.166530,0.356850,0.921710,1.096242,1.998692,-3.054924,5.775000,9.093750,-21.675001,NaN,NaN,2023-06-04 17:36:21,3,8fe3a65e2ea6658d,5
306284,-0.132614,-0.420412,0.089426,0.723854,0.975218,-2.067413,4.556250,11.250000,-20.850000,NaN,NaN,2023-06-04 17:36:22,0,8fe3a65e2ea6658d,5
306285,-1.266848,-1.863428,0.959774,0.106516,0.042301,0.037185,-1.668750,-36.131252,-12.037500,NaN,NaN,2023-06-04 17:36:22,1,8fe3a65e2ea6658d,5
306286,0.098576,0.135542,0.964410,-0.911002,0.562132,0.792269,-2.362500,-34.912502,-12.937501,NaN,NaN,2023-06-04 17:37:08,0,8fe3a65e2ea6658d,5
306287,0.017324,0.217526,0.867298,1.332487,-0.786237,-0.487838,-2.587500,-33.937500,-13.387501,NaN,NaN,2023-06-04 17:37:09,0,8fe3a65e2ea6658d,5
306288,0.016226,-0.091134,1.172664,0.166532,0.110487,-0.005650,-2.512500,-34.256252,-12.150001,NaN,NaN,2023-06-04 17:37:09,1,8fe3a65e2ea6658d,5
306289,0.167994,0.302316,0.871446,0.003589,-0.025579,0.030008,-2.362500,-34.462502,-11.325001,NaN,NaN,2023-06-04 17:37:09,2,8fe3a65e2ea6658d,5
306290,0.065514,0.290970,0.955992,0.145458,-0.115756,0.060016,-2.418750,-34.668751,-10.687500,NaN,NaN,2023-06-04 17:37:09,3,8fe3a65e2ea6658d,5
306291,0.121146,0.321104,0.888526,-0.049708,-0.020998,0.028252,-2.531250,-35.137501,-9.562500,NaN,NaN,2023-06-04 17:37:09,4,8fe3a65e2ea6658d,5
306292,0.196908,0.287920,0.974536,-0.129958,0.028633,-0.136677,-2.531250,-35.250000,-8.662500,NaN,NaN,2023-06-04 17:37:10,0,8fe3a65e2ea6658d,5
306293,0.113094,0.340868,0.873886,0.111174,0.130798,0.012675,-2.325000,-35.718750,-7.668750,NaN,NaN,2023-06-04 17:37:10,1,8fe3a65e2ea6658d,5
306294,0.069296,0.309758,0.921588,-0.068339,-0.229984,-0.065208,-2.043750,-36.525002,-6.600000,NaN,NaN,2023-06-04 17:37:10,2,8fe3a65e2ea6658d,5
306295,0.097478,0.320128,0.941352,-0.028939,0.005192,-0.047952,-1.968750,-37.181252,-6.262500,NaN,NaN,2023-06-04 17:37:10,3,8fe3a65e2ea6658d,5
306296,0.088084,0.358436,0.928298,-0.067422,0.013133,0.031000,-1.912500,-37.837502,-5.887500,NaN,NaN,2023-06-04 17:37:11,0,8fe3a65e2ea6658d,5
306297,0.078446,0.340380,0.959164,0.224105,-0.094605,-0.154010,-1.593750,-39.187500,-5.268750,NaN,NaN,2023-06-04 17:37:11,1,8fe3a65e2ea6658d,5
306298,0.136884,0.341600,0.925614,-0.026190,-0.034055,-0.022525,-1.331250,-39.487503,-5.118750,NaN,NaN,2023-06-04 17:37:11,2,8fe3a65e2ea6658d,5
306299,0.087230,0.350872,0.914390,0.055816,-0.153934,-0.005803,-1.237500,-39.806252,-5.006250,NaN,NaN,2023-06-04 17:37:11,3,8fe3a65e2ea6658d,5
306300,0.152622,0.382958,0.909998,0.001680,0.114076,0.021532,-1.162500,-40.162502,-4.762500,NaN,NaN,2023-06-04 17:37:12,0,8fe3a65e2ea6658d,5
306301,0.153720,0.361364,0.932080,-0.103691,-0.251135,-0.053678,-1.162500,-40.087502,-4.612500,NaN,NaN,2023-06-04 17:37:12,1,8fe3a65e2ea6658d,5
306302,0.151036,0.390156,0.883036,-0.007865,0.105295,-0.006108,-0.993750,-39.581253,-4.518750,NaN,NaN,2023-06-04 17:37:12,2,8fe3a65e2ea6658d,5
306303,0.156648,0.373808,0.880962,-0.048104,-0.065208,0.098117,-0.975000,-39.393753,-4.462500,NaN,NaN,2023-06-04 17:37:12,3,8fe3a65e2ea6658d,5
306304,0.183000,0.366366,0.912438,-0.020998,0.008094,-0.008934,-0.956250,-39.243752,-4.462500,NaN,NaN,2023-06-04 17:37:12,4,8fe3a65e2ea6658d,5
299540,0.423523,0.027664,0.781044,0.347954,0.720723,0.669565,-41.493752,-24.375002,-4.275000,NaN,NaN,2023-06-04 18:48:25,0,8fe3a65e2ea6658d,5
299541,0.416478,0.038857,0.869067,0.378725,1.377002,0.426982,-40.368752,-21.937500,-7.350000,NaN,NaN,2023-06-04 18:48:25,1,8fe3a65e2ea6658d,5
299542,0.129808,0.109068,0.750666,-0.258236,-0.025350,0.089107,-38.681252,-20.906250,-9.937500,NaN,NaN,2023-06-04 18:48:25,2,8fe3a65e2ea6658d,5
299543,0.382348,-0.071492,1.013759,-0.977814,-0.215171,-0.046501,-38.193752,-19.012501,-10.650001,NaN,NaN,2023-06-04 18:48:25,3,8fe3a65e2ea6658d,5
299544,-0.030408,-0.082167,0.377315,4.075115,7.557097,-1.309962,-34.650002,-20.137501,-11.850000,NaN,NaN,2023-06-04 18:48:25,4,8fe3a65e2ea6658d,5
299545,-1.334710,-0.355477,0.040046,-1.287513,0.446682,-3.188241,-27.637501,-22.893751,-9.918751,NaN,NaN,2023-06-04 18:48:26,0,8fe3a65e2ea6658d,5
299546,-1.295793,-0.061152,0.312747,-0.506927,-0.280455,-1.225436,-18.975000,-23.793751,-7.256250,NaN,NaN,2023-06-04 18:48:26,1,8fe3a65e2ea6658d,5
299547,-1.140792,-0.264405,-0.109526,0.699115,0.417896,0.110792,-11.868751,-22.875000,-6.225000,NaN,NaN,2023-06-04 18:48:26,2,8fe3a65e2ea6658d,5
299548,-0.882853,-0.644404,0.084607,-1.030423,-0.190508,1.012861,-0.225000,-25.312502,-1.762500,NaN,NaN,2023-06-04 18:48:26,3,8fe3a65e2ea6658d,5
299549,-0.818315,-0.272273,0.093879,0.284044,0.479286,-0.666358,26.550001,-29.643751,15.412500,NaN,NaN,2023-06-04 18:48:26,4,8fe3a65e2ea6658d,5
299550,-1.181479,-0.367281,-0.010126,1.708463,0.428815,-0.220745,36.056252,-24.768751,22.875000,NaN,NaN,2023-06-04 18:48:27,0,8fe3a65e2ea6658d,5
299551,-0.691984,-0.537562,-0.032299,-1.004844,0.122017,1.064630,42.431252,-20.100000,26.081251,NaN,NaN,2023-06-04 18:48:27,1,8fe3a65e2ea6658d,5
299552,-0.971059,-0.451461,0.205173,2.386657,1.738319,-1.136863,44.812500,-15.300000,27.075001,NaN,NaN,2023-06-04 18:48:27,2,8fe3a65e2ea6658d,5

## Comprobación de datos nulos y no nulos para cada persona

In [6]:
# Replace null values in 'deviceId' column with an invented value (e.g., "UNKNOWN_DEVICE")
invented_device_id = "UNKNOWN_DEVICE"
df['deviceId'] = df['deviceId'].fillna(invented_device_id)

In [7]:
# Agrupar por la columna "deviceId" y calcular el número de datos no nulos por columna
counts = df.groupby("deviceId").count()

# Calcular la suma de valores nulos por columna
null_counts = df.groupby("deviceId").apply(lambda x: x.isnull().sum())

# Mostrar el número de datos no nulos
counts.head(20)

,Ax,Ay,Az,Gx,Gy,Gz,Mx,My,Mz,Bpressure,Lilluminance,timestamp,counter,activity
deviceId,,,,,,,,,,,,,,
5a287c6d3ffda73f,1112,1112,1112,1045,1045,1045,1059,1059,1059,1052,1031,1181,1184,1184
629b502066d8a33a,220,220,220,157,157,157,157,157,157,0,194,235,235,235
73d32f5bb75976e4,1098,1098,1098,1058,1058,1058,1091,1091,1091,0,976,1139,1144,1144
8fe3a65e2ea6658d,9965,9965,9965,9363,9363,9363,9454,9454,9454,0,0,10340,10346,10346
TP1A.220624.014,156073,156073,156073,154371,154371,154371,123779,123779,123779,0,16890,156519,156525,156525
UNKNOWN_DEVICE,130403,130403,130403,129082,129082,129082,129215,129215,129215,0,0,131128,131134,131134
b719b9175e5338b9,385,385,385,409,409,409,304,304,304,0,177,469,472,472
b973ac361183cbb0,616,616,616,555,555,555,591,591,591,0,461,693,693,693
bebf6a9bfd30c163,695,695,695,664,664,664,674,674,674,0,668,741,742,742
c32bdcc96f9e1fb1,768,768,768,746,746,746,576,576,576,0,460,839,842,842
ccbc9d76c2ebeaf5,1239,1239,1239,974,974,974,987,987,987,958,939,1358,1358,1358
d99f0327fa491f9f,4939,4939,4939,4679,4679,4679,4208,4208,4208,4542,1785,5030,5033,5033

In [8]:
# Mostrar el número de datos nulos
null_counts.head(20)

,Ax,Ay,Az,Gx,Gy,Gz,Mx,My,Mz,Bpressure,Lilluminance,timestamp,counter,deviceId,activity
deviceId,,,,,,,,,,,,,,,
5a287c6d3ffda73f,72,72,72,139,139,139,125,125,125,132,153,3,0,0,0
629b502066d8a33a,15,15,15,78,78,78,78,78,78,235,41,0,0,0,0
73d32f5bb75976e4,46,46,46,86,86,86,53,53,53,1144,168,5,0,0,0
8fe3a65e2ea6658d,381,381,381,983,983,983,892,892,892,10346,10346,6,0,0,0
TP1A.220624.014,452,452,452,2154,2154,2154,32746,32746,32746,156525,139635,6,0,0,0
UNKNOWN_DEVICE,731,731,731,2052,2052,2052,1919,1919,1919,131134,131134,6,0,0,0
b719b9175e5338b9,87,87,87,63,63,63,168,168,168,472,295,3,0,0,0
b973ac361183cbb0,77,77,77,138,138,138,102,102,102,693,232,0,0,0,0
bebf6a9bfd30c163,47,47,47,78,78,78,68,68,68,742,74,1,0,0,0
c32bdcc96f9e1fb1,74,74,74,96,96,96,266,266,266,842,382,3,0,0,0
ccbc9d76c2ebeaf5,119,119,119,384,384,384,371,371,371,400,419,0,0,0,0
d99f0327fa491f9f,94,94,94,354,354,354,825,825,825,491,3248,3,0,0,0

## Selección de persona para analizar los datos

In [9]:
# Especificar el deviceId que deseas seleccionar
device_id = '8fe3a65e2ea6658d'

# Filtrar el DataFrame por el deviceId específico
device_data = df[df['deviceId'] == device_id]

## Comprobar si una de las columnas solo tiene valores nulos

In [10]:
# Verificar si alguna columna tiene solo valores no nulos
columnas_no_null = df.notnull().all()
print(columnas_no_null)

Ax              False
Ay              False
Az              False
Gx              False
Gy              False
Gz              False
Mx              False
My              False
Mz              False
Bpressure       False
Lilluminance    False
timestamp       False
counter          True
deviceId         True
activity         True
dtype: bool

## Comprobación de las columnas del sensor Acelerómetro

In [11]:
cantidad_nulos = df[['Ax', 'Ay', 'Az']].isnull().sum()
print(cantidad_nulos)

Ax    2195
Ay    2195
Az    2195
dtype: int64

In [12]:
# Agrupar por 'activity'
grouped = df.groupby('activity')

# Resetear el índice del DataFrame antes de aplicar la interpolación
df.reset_index(drop=True, inplace=True)

# Rellenar los valores nulos con la media entre el valor anterior y posterior
df[['Ax', 'Ay', 'Az']] = grouped[['Ax', 'Ay', 'Az']].apply(lambda x: x.interpolate().fillna(method='bfill'))

df.head(40)

,Ax,Ay,Az,Gx,Gy,Gz,Mx,My,Mz,Bpressure,Lilluminance,timestamp,counter,deviceId,activity
0,-0.097234,0.418460,0.843996,0.286335,0.070782,0.084450,-1.368750,8.156250,-24.168751,NaN,NaN,2023-06-04 17:36:20,0,8fe3a65e2ea6658d,5
1,0.249002,0.293410,1.201944,-0.177069,0.058947,0.357040,-1.443750,8.193750,-24.300001,NaN,NaN,2023-06-04 17:36:20,1,8fe3a65e2ea6658d,5
2,0.240584,0.380152,1.015406,-0.172335,1.051955,0.423623,0.131250,8.212501,-23.943750,NaN,NaN,2023-06-04 17:36:21,0,8fe3a65e2ea6658d,5
3,0.113704,0.335500,0.834236,-0.159355,0.307867,0.560376,1.837500,8.400001,-23.400002,NaN,NaN,2023-06-04 17:36:21,1,8fe3a65e2ea6658d,5
4,0.038308,0.284992,0.928786,0.300766,0.246171,0.454623,3.618750,8.100000,-23.025002,NaN,NaN,2023-06-04 17:36:21,2,8fe3a65e2ea6658d,5
5,-0.166530,0.356850,0.921710,1.096242,1.998692,-3.054924,5.775000,9.093750,-21.675001,NaN,NaN,2023-06-04 17:36:21,3,8fe3a65e2ea6658d,5
6,-0.132614,-0.420412,0.089426,0.723854,0.975218,-2.067413,4.556250,11.250000,-20.850000,NaN,NaN,2023-06-04 17:36:22,0,8fe3a65e2ea6658d,5
7,-1.266848,-1.863428,0.959774,0.106516,0.042301,0.037185,-1.668750,-36.131252,-12.037500,NaN,NaN,2023-06-04 17:36:22,1,8fe3a65e2ea6658d,5
8,0.098576,0.135542,0.964410,-0.911002,0.562132,0.792269,-2.362500,-34.912502,-12.937501,NaN,NaN,2023-06-04 17:37:08,0,8fe3a65e2ea6658d,5
9,0.017324,0.217526,0.867298,1.332487,-0.786237,-0.487838,-2.587500,-33.937500,-13.387501,NaN,NaN,2023-06-04 17:37:09,0,8fe3a65e2ea6658d,5
10,0.016226,-0.091134,1.172664,0.166532,0.110487,-0.005650,-2.512500,-34.256252,-12.150001,NaN,NaN,2023-06-04 17:37:09,1,8fe3a65e2ea6658d,5
11,0.167994,0.302316,0.871446,0.003589,-0.025579,0.030008,-2.362500,-34.462502,-11.325001,NaN,NaN,2023-06-04 17:37:09,2,8fe3a65e2ea6658d,5
12,0.065514,0.290970,0.955992,0.145458,-0.115756,0.060016,-2.418750,-34.668751,-10.687500,NaN,NaN,2023-06-04 17:37:09,3,8fe3a65e2ea6658d,5
13,0.121146,0.321104,0.888526,-0.049708,-0.020998,0.028252,-2.531250,-35.137501,-9.562500,NaN,NaN,2023-06-04 17:37:09,4,8fe3a65e2ea6658d,5
14,0.196908,0.287920,0.974536,-0.129958,0.028633,-0.136677,-2.531250,-35.250000,-8.662500,NaN,NaN,2023-06-04 17:37:10,0,8fe3a65e2ea6658d,5
15,0.113094,0.340868,0.873886,0.111174,0.130798,0.012675,-2.325000,-35.718750,-7.668750,NaN,NaN,2023-06-04 17:37:10,1,8fe3a65e2ea6658d,5
16,0.069296,0.309758,0.921588,-0.068339,-0.229984,-0.065208,-2.043750,-36.525002,-6.600000,NaN,NaN,2023-06-04 17:37:10,2,8fe3a65e2ea6658d,5
17,0.097478,0.320128,0.941352,-0.028939,0.005192,-0.047952,-1.968750,-37.181252,-6.262500,NaN,NaN,2023-06-04 17:37:10,3,8fe3a65e2ea6658d,5
18,0.088084,0.358436,0.928298,-0.067422,0.013133,0.031000,-1.912500,-37.837502,-5.887500,NaN,NaN,2023-06-04 17:37:11,0,8fe3a65e2ea6658d,5
19,0.078446,0.340380,0.959164,0.224105,-0.094605,-0.154010,-1.593750,-39.187500,-5.268750,NaN,NaN,2023-06-04 17:37:11,1,8fe3a65e2ea6658d,5
20,0.136884,0.341600,0.925614,-0.026190,-0.034055,-0.022525,-1.331250,-39.487503,-5.118750,NaN,NaN,2023-06-04 17:37:11,2,8fe3a65e2ea6658d,5
21,0.087230,0.350872,0.914390,0.055816,-0.153934,-0.005803,-1.237500,-39.806252,-5.006250,NaN,NaN,2023-06-04 17:37:11,3,8fe3a65e2ea6658d,5
22,0.152622,0.382958,0.909998,0.001680,0.114076,0.021532,-1.162500,-40.162502,-4.762500,NaN,NaN,2023-06-04 17:37:12,0,8fe3a65e2ea6658d,5
23,0.153720,0.361364,0.932080,-0.103691,-0.251135,-0.053678,-1.162500,-40.087502,-4.612500,NaN,NaN,2023-06-04 17:37:12,1,8fe3a65e2ea6658d,5
24,0.151036,0.390156,0.883036,-0.007865,0.105295,-0.006108,-0.993750,-39.581253,-4.518750,NaN,NaN,2023-06-04 17:37:12,2,8fe3a65e2ea6658d,5
25,0.156648,0.373808,0.880962,-0.048104,-0.065208,0.098117,-0.975000,-39.393753,-4.462500,NaN,NaN,2023-06-04 17:37:12,3,8fe3a65e2ea6658d,5
26,0.183000,0.366366,0.912438,-0.020998,0.008094,-0.008934,-0.956250,-39.243752,-4.462500,NaN,NaN,2023-06-04 17:37:12,4,8fe3a65e2ea6658d,5
27,0.423523,0.027664,0.781044,0.347954,0.720723,0.669565,-41.493752,-24.375002,-4.275000,NaN,NaN,2023-06-04 18:48:25,0,8fe3a65e2ea6658d,5
28,0.416478,0.038857,0.869067,0.378725,1.377002,0.426982,-40.368752,-21.937500,-7.350000,NaN,NaN,2023-06-04 18:48:25,1,8fe3a65e2ea6658d,5
29,0.129808,0.109068,0.750666,-0.258236,-0.025350,0.089107,-38.681252,-20.906250,-9.937500,NaN,NaN,2023-06-04 18:48:25,2,8fe3a65e2ea6658d,5
30,0.382348,-0.071492,1.013759,-0.977814,-0.215171,-0.046501,-38.193752,-19.012501,-10.650001,NaN,NaN,2023-06-04 18:48:25,3,8fe3a65e2ea6658d,5
31,-0.030408,-0.082167,0.377315,4.075115,7.557097,-1.309962,-34.650002,-20.137501,-11.850000,NaN,NaN,2023-06-04 18:48:25,4,8fe3a65e2ea6658d,5
32,-1.334710,-0.355477,0.040046,-1.287513,0.446682,-3.188241,-27.637501,-22.893751,-9.918751,NaN,NaN,2023-06-04 18:48:26,0,8fe3a65e2ea6658d,5
33,-1.295793,-0.061152,0.312747,-0.506927,-0.280455,-1.225436,-18.975000,-23.793751,-7.256250,NaN,NaN,2023-06-04 18:48:26,1,8fe3a65e2ea6658d,5
34,-1.140792,-0.264405,-0.109526,0.699115,0.417896,0.110792,-11.868751,-22.875000,-6.225000,NaN,NaN,2023-06-04 18:48:26,2,8fe3a65e2ea6658d,5
35,-0.882853,-0.644404,0.084607,-1.030423,-0.190508,1.012861,-0.225000,-25.312502,-1.762500,NaN,NaN,2023-06-04 18:48:26,3,8fe3a65e2ea6658d,5
36,-0.818315,-0.272273,0.093879,0.284044,0.479286,-0.666358,26.550001,-29.643751,15.412500,NaN,NaN,2023-06-04 18:48:26,4,8fe3a65e2ea6658d,5
37,-1.181479,-0.367281,-0.010126,1.708463,0.428815,-0.220745,36.056252,-24.768751,22.875000,NaN,NaN,2023-06-04 18:48:27,0,8fe3a65e2ea6658d,5
38,-0.691984,-0.537562,-0.032299,-1.004844,0.122017,1.064630,42.431252,-20.100000,26.081251,NaN,NaN,2023-06-04 18:48:27,1,8fe3a65e2ea6658d,5
39,-0.971059,-0.451461,0.205173,2.386657,1.738319,-1.136863,44.812500,-15.300000,27.075001,NaN,NaN,2023-06-04 18:48:27,2,8fe3a65e2ea6658d,5

In [13]:
cantidad_nulos = df[['Ax', 'Ay', 'Az']].isnull().sum()
print(cantidad_nulos)

Ax    0
Ay    0
Az    0
dtype: int64

## Comprobación de las columnas del sensor Giroscopio

In [14]:
cantidad_nulos = df[['Gx', 'Gy', 'Gz']].isnull().sum()
print(cantidad_nulos)

Gx    6605
Gy    6605
Gz    6605
dtype: int64

In [15]:
# Agrupar por 'activity'
grouped = df.groupby('activity')

# Rellenar los valores nulos con la media entre el valor anterior y posterior
df[['Gx', 'Gy', 'Gz']] = grouped[['Gx', 'Gy', 'Gz']].apply(lambda x: x.interpolate().fillna(method='bfill'))

df.head(40)

,Ax,Ay,Az,Gx,Gy,Gz,Mx,My,Mz,Bpressure,Lilluminance,timestamp,counter,deviceId,activity
0,-0.097234,0.418460,0.843996,0.286335,0.070782,0.084450,-1.368750,8.156250,-24.168751,NaN,NaN,2023-06-04 17:36:20,0,8fe3a65e2ea6658d,5
1,0.249002,0.293410,1.201944,-0.177069,0.058947,0.357040,-1.443750,8.193750,-24.300001,NaN,NaN,2023-06-04 17:36:20,1,8fe3a65e2ea6658d,5
2,0.240584,0.380152,1.015406,-0.172335,1.051955,0.423623,0.131250,8.212501,-23.943750,NaN,NaN,2023-06-04 17:36:21,0,8fe3a65e2ea6658d,5
3,0.113704,0.335500,0.834236,-0.159355,0.307867,0.560376,1.837500,8.400001,-23.400002,NaN,NaN,2023-06-04 17:36:21,1,8fe3a65e2ea6658d,5
4,0.038308,0.284992,0.928786,0.300766,0.246171,0.454623,3.618750,8.100000,-23.025002,NaN,NaN,2023-06-04 17:36:21,2,8fe3a65e2ea6658d,5
5,-0.166530,0.356850,0.921710,1.096242,1.998692,-3.054924,5.775000,9.093750,-21.675001,NaN,NaN,2023-06-04 17:36:21,3,8fe3a65e2ea6658d,5
6,-0.132614,-0.420412,0.089426,0.723854,0.975218,-2.067413,4.556250,11.250000,-20.850000,NaN,NaN,2023-06-04 17:36:22,0,8fe3a65e2ea6658d,5
7,-1.266848,-1.863428,0.959774,0.106516,0.042301,0.037185,-1.668750,-36.131252,-12.037500,NaN,NaN,2023-06-04 17:36:22,1,8fe3a65e2ea6658d,5
8,0.098576,0.135542,0.964410,-0.911002,0.562132,0.792269,-2.362500,-34.912502,-12.937501,NaN,NaN,2023-06-04 17:37:08,0,8fe3a65e2ea6658d,5
9,0.017324,0.217526,0.867298,1.332487,-0.786237,-0.487838,-2.587500,-33.937500,-13.387501,NaN,NaN,2023-06-04 17:37:09,0,8fe3a65e2ea6658d,5
10,0.016226,-0.091134,1.172664,0.166532,0.110487,-0.005650,-2.512500,-34.256252,-12.150001,NaN,NaN,2023-06-04 17:37:09,1,8fe3a65e2ea6658d,5
11,0.167994,0.302316,0.871446,0.003589,-0.025579,0.030008,-2.362500,-34.462502,-11.325001,NaN,NaN,2023-06-04 17:37:09,2,8fe3a65e2ea6658d,5
12,0.065514,0.290970,0.955992,0.145458,-0.115756,0.060016,-2.418750,-34.668751,-10.687500,NaN,NaN,2023-06-04 17:37:09,3,8fe3a65e2ea6658d,5
13,0.121146,0.321104,0.888526,-0.049708,-0.020998,0.028252,-2.531250,-35.137501,-9.562500,NaN,NaN,2023-06-04 17:37:09,4,8fe3a65e2ea6658d,5
14,0.196908,0.287920,0.974536,-0.129958,0.028633,-0.136677,-2.531250,-35.250000,-8.662500,NaN,NaN,2023-06-04 17:37:10,0,8fe3a65e2ea6658d,5
15,0.113094,0.340868,0.873886,0.111174,0.130798,0.012675,-2.325000,-35.718750,-7.668750,NaN,NaN,2023-06-04 17:37:10,1,8fe3a65e2ea6658d,5
16,0.069296,0.309758,0.921588,-0.068339,-0.229984,-0.065208,-2.043750,-36.525002,-6.600000,NaN,NaN,2023-06-04 17:37:10,2,8fe3a65e2ea6658d,5
17,0.097478,0.320128,0.941352,-0.028939,0.005192,-0.047952,-1.968750,-37.181252,-6.262500,NaN,NaN,2023-06-04 17:37:10,3,8fe3a65e2ea6658d,5
18,0.088084,0.358436,0.928298,-0.067422,0.013133,0.031000,-1.912500,-37.837502,-5.887500,NaN,NaN,2023-06-04 17:37:11,0,8fe3a65e2ea6658d,5
19,0.078446,0.340380,0.959164,0.224105,-0.094605,-0.154010,-1.593750,-39.187500,-5.268750,NaN,NaN,2023-06-04 17:37:11,1,8fe3a65e2ea6658d,5
20,0.136884,0.341600,0.925614,-0.026190,-0.034055,-0.022525,-1.331250,-39.487503,-5.118750,NaN,NaN,2023-06-04 17:37:11,2,8fe3a65e2ea6658d,5
21,0.087230,0.350872,0.914390,0.055816,-0.153934,-0.005803,-1.237500,-39.806252,-5.006250,NaN,NaN,2023-06-04 17:37:11,3,8fe3a65e2ea6658d,5
22,0.152622,0.382958,0.909998,0.001680,0.114076,0.021532,-1.162500,-40.162502,-4.762500,NaN,NaN,2023-06-04 17:37:12,0,8fe3a65e2ea6658d,5
23,0.153720,0.361364,0.932080,-0.103691,-0.251135,-0.053678,-1.162500,-40.087502,-4.612500,NaN,NaN,2023-06-04 17:37:12,1,8fe3a65e2ea6658d,5
24,0.151036,0.390156,0.883036,-0.007865,0.105295,-0.006108,-0.993750,-39.581253,-4.518750,NaN,NaN,2023-06-04 17:37:12,2,8fe3a65e2ea6658d,5
25,0.156648,0.373808,0.880962,-0.048104,-0.065208,0.098117,-0.975000,-39.393753,-4.462500,NaN,NaN,2023-06-04 17:37:12,3,8fe3a65e2ea6658d,5
26,0.183000,0.366366,0.912438,-0.020998,0.008094,-0.008934,-0.956250,-39.243752,-4.462500,NaN,NaN,2023-06-04 17:37:12,4,8fe3a65e2ea6658d,5
27,0.423523,0.027664,0.781044,0.347954,0.720723,0.669565,-41.493752,-24.375002,-4.275000,NaN,NaN,2023-06-04 18:48:25,0,8fe3a65e2ea6658d,5
28,0.416478,0.038857,0.869067,0.378725,1.377002,0.426982,-40.368752,-21.937500,-7.350000,NaN,NaN,2023-06-04 18:48:25,1,8fe3a65e2ea6658d,5
29,0.129808,0.109068,0.750666,-0.258236,-0.025350,0.089107,-38.681252,-20.906250,-9.937500,NaN,NaN,2023-06-04 18:48:25,2,8fe3a65e2ea6658d,5
30,0.382348,-0.071492,1.013759,-0.977814,-0.215171,-0.046501,-38.193752,-19.012501,-10.650001,NaN,NaN,2023-06-04 18:48:25,3,8fe3a65e2ea6658d,5
31,-0.030408,-0.082167,0.377315,4.075115,7.557097,-1.309962,-34.650002,-20.137501,-11.850000,NaN,NaN,2023-06-04 18:48:25,4,8fe3a65e2ea6658d,5
32,-1.334710,-0.355477,0.040046,-1.287513,0.446682,-3.188241,-27.637501,-22.893751,-9.918751,NaN,NaN,2023-06-04 18:48:26,0,8fe3a65e2ea6658d,5
33,-1.295793,-0.061152,0.312747,-0.506927,-0.280455,-1.225436,-18.975000,-23.793751,-7.256250,NaN,NaN,2023-06-04 18:48:26,1,8fe3a65e2ea6658d,5
34,-1.140792,-0.264405,-0.109526,0.699115,0.417896,0.110792,-11.868751,-22.875000,-6.225000,NaN,NaN,2023-06-04 18:48:26,2,8fe3a65e2ea6658d,5
35,-0.882853,-0.644404,0.084607,-1.030423,-0.190508,1.012861,-0.225000,-25.312502,-1.762500,NaN,NaN,2023-06-04 18:48:26,3,8fe3a65e2ea6658d,5
36,-0.818315,-0.272273,0.093879,0.284044,0.479286,-0.666358,26.550001,-29.643751,15.412500,NaN,NaN,2023-06-04 18:48:26,4,8fe3a65e2ea6658d,5
37,-1.181479,-0.367281,-0.010126,1.708463,0.428815,-0.220745,36.056252,-24.768751,22.875000,NaN,NaN,2023-06-04 18:48:27,0,8fe3a65e2ea6658d,5
38,-0.691984,-0.537562,-0.032299,-1.004844,0.122017,1.064630,42.431252,-20.100000,26.081251,NaN,NaN,2023-06-04 18:48:27,1,8fe3a65e2ea6658d,5
39,-0.971059,-0.451461,0.205173,2.386657,1.738319,-1.136863,44.812500,-15.300000,27.075001,NaN,NaN,2023-06-04 18:48:27,2,8fe3a65e2ea6658d,5

In [16]:
cantidad_nulos = df[['Gx', 'Gy', 'Gz']].isnull().sum()
print(cantidad_nulos)

Gx    0
Gy    0
Gz    0
dtype: int64

## Comprobación de las columnas del sensor Magnetrómetro

In [17]:
cantidad_nulos = df[['Mx', 'My', 'Mz']].isnull().sum()
print(cantidad_nulos)

Mx    37613
My    37613
Mz    37613
dtype: int64

In [18]:
# Agrupar por 'activity'
grouped = df.groupby('activity')

# Rellenar los valores nulos con la media entre el valor anterior y posterior
df[['Mx', 'My', 'Mz']] = grouped[['Mx', 'My', 'Mz']].apply(lambda x: x.interpolate().fillna(method='bfill'))

df.head(40)

,Ax,Ay,Az,Gx,Gy,Gz,Mx,My,Mz,Bpressure,Lilluminance,timestamp,counter,deviceId,activity
0,-0.097234,0.418460,0.843996,0.286335,0.070782,0.084450,-1.368750,8.156250,-24.168751,NaN,NaN,2023-06-04 17:36:20,0,8fe3a65e2ea6658d,5
1,0.249002,0.293410,1.201944,-0.177069,0.058947,0.357040,-1.443750,8.193750,-24.300001,NaN,NaN,2023-06-04 17:36:20,1,8fe3a65e2ea6658d,5
2,0.240584,0.380152,1.015406,-0.172335,1.051955,0.423623,0.131250,8.212501,-23.943750,NaN,NaN,2023-06-04 17:36:21,0,8fe3a65e2ea6658d,5
3,0.113704,0.335500,0.834236,-0.159355,0.307867,0.560376,1.837500,8.400001,-23.400002,NaN,NaN,2023-06-04 17:36:21,1,8fe3a65e2ea6658d,5
4,0.038308,0.284992,0.928786,0.300766,0.246171,0.454623,3.618750,8.100000,-23.025002,NaN,NaN,2023-06-04 17:36:21,2,8fe3a65e2ea6658d,5
5,-0.166530,0.356850,0.921710,1.096242,1.998692,-3.054924,5.775000,9.093750,-21.675001,NaN,NaN,2023-06-04 17:36:21,3,8fe3a65e2ea6658d,5
6,-0.132614,-0.420412,0.089426,0.723854,0.975218,-2.067413,4.556250,11.250000,-20.850000,NaN,NaN,2023-06-04 17:36:22,0,8fe3a65e2ea6658d,5
7,-1.266848,-1.863428,0.959774,0.106516,0.042301,0.037185,-1.668750,-36.131252,-12.037500,NaN,NaN,2023-06-04 17:36:22,1,8fe3a65e2ea6658d,5
8,0.098576,0.135542,0.964410,-0.911002,0.562132,0.792269,-2.362500,-34.912502,-12.937501,NaN,NaN,2023-06-04 17:37:08,0,8fe3a65e2ea6658d,5
9,0.017324,0.217526,0.867298,1.332487,-0.786237,-0.487838,-2.587500,-33.937500,-13.387501,NaN,NaN,2023-06-04 17:37:09,0,8fe3a65e2ea6658d,5
10,0.016226,-0.091134,1.172664,0.166532,0.110487,-0.005650,-2.512500,-34.256252,-12.150001,NaN,NaN,2023-06-04 17:37:09,1,8fe3a65e2ea6658d,5
11,0.167994,0.302316,0.871446,0.003589,-0.025579,0.030008,-2.362500,-34.462502,-11.325001,NaN,NaN,2023-06-04 17:37:09,2,8fe3a65e2ea6658d,5
12,0.065514,0.290970,0.955992,0.145458,-0.115756,0.060016,-2.418750,-34.668751,-10.687500,NaN,NaN,2023-06-04 17:37:09,3,8fe3a65e2ea6658d,5
13,0.121146,0.321104,0.888526,-0.049708,-0.020998,0.028252,-2.531250,-35.137501,-9.562500,NaN,NaN,2023-06-04 17:37:09,4,8fe3a65e2ea6658d,5
14,0.196908,0.287920,0.974536,-0.129958,0.028633,-0.136677,-2.531250,-35.250000,-8.662500,NaN,NaN,2023-06-04 17:37:10,0,8fe3a65e2ea6658d,5
15,0.113094,0.340868,0.873886,0.111174,0.130798,0.012675,-2.325000,-35.718750,-7.668750,NaN,NaN,2023-06-04 17:37:10,1,8fe3a65e2ea6658d,5
16,0.069296,0.309758,0.921588,-0.068339,-0.229984,-0.065208,-2.043750,-36.525002,-6.600000,NaN,NaN,2023-06-04 17:37:10,2,8fe3a65e2ea6658d,5
17,0.097478,0.320128,0.941352,-0.028939,0.005192,-0.047952,-1.968750,-37.181252,-6.262500,NaN,NaN,2023-06-04 17:37:10,3,8fe3a65e2ea6658d,5
18,0.088084,0.358436,0.928298,-0.067422,0.013133,0.031000,-1.912500,-37.837502,-5.887500,NaN,NaN,2023-06-04 17:37:11,0,8fe3a65e2ea6658d,5
19,0.078446,0.340380,0.959164,0.224105,-0.094605,-0.154010,-1.593750,-39.187500,-5.268750,NaN,NaN,2023-06-04 17:37:11,1,8fe3a65e2ea6658d,5
20,0.136884,0.341600,0.925614,-0.026190,-0.034055,-0.022525,-1.331250,-39.487503,-5.118750,NaN,NaN,2023-06-04 17:37:11,2,8fe3a65e2ea6658d,5
21,0.087230,0.350872,0.914390,0.055816,-0.153934,-0.005803,-1.237500,-39.806252,-5.006250,NaN,NaN,2023-06-04 17:37:11,3,8fe3a65e2ea6658d,5
22,0.152622,0.382958,0.909998,0.001680,0.114076,0.021532,-1.162500,-40.162502,-4.762500,NaN,NaN,2023-06-04 17:37:12,0,8fe3a65e2ea6658d,5
23,0.153720,0.361364,0.932080,-0.103691,-0.251135,-0.053678,-1.162500,-40.087502,-4.612500,NaN,NaN,2023-06-04 17:37:12,1,8fe3a65e2ea6658d,5
24,0.151036,0.390156,0.883036,-0.007865,0.105295,-0.006108,-0.993750,-39.581253,-4.518750,NaN,NaN,2023-06-04 17:37:12,2,8fe3a65e2ea6658d,5
25,0.156648,0.373808,0.880962,-0.048104,-0.065208,0.098117,-0.975000,-39.393753,-4.462500,NaN,NaN,2023-06-04 17:37:12,3,8fe3a65e2ea6658d,5
26,0.183000,0.366366,0.912438,-0.020998,0.008094,-0.008934,-0.956250,-39.243752,-4.462500,NaN,NaN,2023-06-04 17:37:12,4,8fe3a65e2ea6658d,5
27,0.423523,0.027664,0.781044,0.347954,0.720723,0.669565,-41.493752,-24.375002,-4.275000,NaN,NaN,2023-06-04 18:48:25,0,8fe3a65e2ea6658d,5
28,0.416478,0.038857,0.869067,0.378725,1.377002,0.426982,-40.368752,-21.937500,-7.350000,NaN,NaN,2023-06-04 18:48:25,1,8fe3a65e2ea6658d,5
29,0.129808,0.109068,0.750666,-0.258236,-0.025350,0.089107,-38.681252,-20.906250,-9.937500,NaN,NaN,2023-06-04 18:48:25,2,8fe3a65e2ea6658d,5
30,0.382348,-0.071492,1.013759,-0.977814,-0.215171,-0.046501,-38.193752,-19.012501,-10.650001,NaN,NaN,2023-06-04 18:48:25,3,8fe3a65e2ea6658d,5
31,-0.030408,-0.082167,0.377315,4.075115,7.557097,-1.309962,-34.650002,-20.137501,-11.850000,NaN,NaN,2023-06-04 18:48:25,4,8fe3a65e2ea6658d,5
32,-1.334710,-0.355477,0.040046,-1.287513,0.446682,-3.188241,-27.637501,-22.893751,-9.918751,NaN,NaN,2023-06-04 18:48:26,0,8fe3a65e2ea6658d,5
33,-1.295793,-0.061152,0.312747,-0.506927,-0.280455,-1.225436,-18.975000,-23.793751,-7.256250,NaN,NaN,2023-06-04 18:48:26,1,8fe3a65e2ea6658d,5
34,-1.140792,-0.264405,-0.109526,0.699115,0.417896,0.110792,-11.868751,-22.875000,-6.225000,NaN,NaN,2023-06-04 18:48:26,2,8fe3a65e2ea6658d,5
35,-0.882853,-0.644404,0.084607,-1.030423,-0.190508,1.012861,-0.225000,-25.312502,-1.762500,NaN,NaN,2023-06-04 18:48:26,3,8fe3a65e2ea6658d,5
36,-0.818315,-0.272273,0.093879,0.284044,0.479286,-0.666358,26.550001,-29.643751,15.412500,NaN,NaN,2023-06-04 18:48:26,4,8fe3a65e2ea6658d,5
37,-1.181479,-0.367281,-0.010126,1.708463,0.428815,-0.220745,36.056252,-24.768751,22.875000,NaN,NaN,2023-06-04 18:48:27,0,8fe3a65e2ea6658d,5
38,-0.691984,-0.537562,-0.032299,-1.004844,0.122017,1.064630,42.431252,-20.100000,26.081251,NaN,NaN,2023-06-04 18:48:27,1,8fe3a65e2ea6658d,5
39,-0.971059,-0.451461,0.205173,2.386657,1.738319,-1.136863,44.812500,-15.300000,27.075001,NaN,NaN,2023-06-04 18:48:27,2,8fe3a65e2ea6658d,5

In [19]:
cantidad_nulos = df[['Mx', 'My', 'Mz']].isnull().sum()
print(cantidad_nulos)

Mx    0
My    0
Mz    0
dtype: int64

## Comprobación de la columna timestamp

In [20]:
cantidad_nulos = df[['timestamp']].isnull().sum()
print(cantidad_nulos)

timestamp    36
dtype: int64

In [21]:
# Convertir la columna 'timestamp' a tipo datetime
df['timestamp'] = pd.to_datetime(df['timestamp'])

# Obtener el timestamp en minutos desde la época (1970-01-01 00:00:00)
df['timestamp'] = df['timestamp'].astype(int) // (10**9 * 60)

# Verificar los cambios
print(df['timestamp'])

0          28098336
1          28098336
2          28098336
3          28098336
4          28098336
            ...
309703   -153722868
309704   -153722868
309705   -153722868
309706   -153722868
309707   -153722868
Name: timestamp, Length: 309708, dtype: int64

/tmp/ipykernel_104655/1046296482.py:5: FutureWarning: casting datetime64[ns] values to int64 with .astype(...) is deprecated and will raise in a future version. Use .view(...) instead.
  df['timestamp'] = df['timestamp'].astype(int) // (10**9 * 60)

In [22]:
# Agrupar por 'activity'
grouped = df.groupby('activity')

# Rellenar los valores nulos con la media entre el valor anterior y posterior
df[['timestamp']] = grouped[['timestamp']].apply(lambda x: x.interpolate().fillna(method='bfill'))

In [23]:
cantidad_nulos = df[['timestamp']].isnull().sum()
print(cantidad_nulos)

timestamp    0
dtype: int64

## Comprobación de los sensores Barómetro y Luminancia

In [24]:
cantidad_nulos = df[['Bpressure', 'Lilluminance']].isnull().sum()
print(cantidad_nulos)

Bpressure       303156
Lilluminance    286127
dtype: int64

In [25]:
# Agrupar por 'activity'
grouped = df.groupby('activity')

# Rellenar los valores nulos con la media entre el valor anterior y posterior
df[['Bpressure', 'Lilluminance']] = grouped[['Bpressure', 'Lilluminance']].apply(lambda x: x.interpolate().fillna(method='bfill'))

df.head(40)

,Ax,Ay,Az,Gx,Gy,Gz,Mx,My,Mz,Bpressure,Lilluminance,timestamp,counter,deviceId,activity
0,-0.097234,0.418460,0.843996,0.286335,0.070782,0.084450,-1.368750,8.156250,-24.168751,943.964355,85.940033,28098336,0,8fe3a65e2ea6658d,5
1,0.249002,0.293410,1.201944,-0.177069,0.058947,0.357040,-1.443750,8.193750,-24.300001,943.964355,85.940033,28098336,1,8fe3a65e2ea6658d,5
2,0.240584,0.380152,1.015406,-0.172335,1.051955,0.423623,0.131250,8.212501,-23.943750,943.964355,85.940033,28098336,0,8fe3a65e2ea6658d,5
3,0.113704,0.335500,0.834236,-0.159355,0.307867,0.560376,1.837500,8.400001,-23.400002,943.964355,85.940033,28098336,1,8fe3a65e2ea6658d,5
4,0.038308,0.284992,0.928786,0.300766,0.246171,0.454623,3.618750,8.100000,-23.025002,943.964355,85.940033,28098336,2,8fe3a65e2ea6658d,5
5,-0.166530,0.356850,0.921710,1.096242,1.998692,-3.054924,5.775000,9.093750,-21.675001,943.964355,85.940033,28098336,3,8fe3a65e2ea6658d,5
6,-0.132614,-0.420412,0.089426,0.723854,0.975218,-2.067413,4.556250,11.250000,-20.850000,943.964355,85.940033,28098336,0,8fe3a65e2ea6658d,5
7,-1.266848,-1.863428,0.959774,0.106516,0.042301,0.037185,-1.668750,-36.131252,-12.037500,943.964355,85.940033,28098336,1,8fe3a65e2ea6658d,5
8,0.098576,0.135542,0.964410,-0.911002,0.562132,0.792269,-2.362500,-34.912502,-12.937501,943.964355,85.940033,28098337,0,8fe3a65e2ea6658d,5
9,0.017324,0.217526,0.867298,1.332487,-0.786237,-0.487838,-2.587500,-33.937500,-13.387501,943.964355,85.940033,28098337,0,8fe3a65e2ea6658d,5
10,0.016226,-0.091134,1.172664,0.166532,0.110487,-0.005650,-2.512500,-34.256252,-12.150001,943.964355,85.940033,28098337,1,8fe3a65e2ea6658d,5
11,0.167994,0.302316,0.871446,0.003589,-0.025579,0.030008,-2.362500,-34.462502,-11.325001,943.964355,85.940033,28098337,2,8fe3a65e2ea6658d,5
12,0.065514,0.290970,0.955992,0.145458,-0.115756,0.060016,-2.418750,-34.668751,-10.687500,943.964355,85.940033,28098337,3,8fe3a65e2ea6658d,5
13,0.121146,0.321104,0.888526,-0.049708,-0.020998,0.028252,-2.531250,-35.137501,-9.562500,943.964355,85.940033,28098337,4,8fe3a65e2ea6658d,5
14,0.196908,0.287920,0.974536,-0.129958,0.028633,-0.136677,-2.531250,-35.250000,-8.662500,943.964355,85.940033,28098337,0,8fe3a65e2ea6658d,5
15,0.113094,0.340868,0.873886,0.111174,0.130798,0.012675,-2.325000,-35.718750,-7.668750,943.964355,85.940033,28098337,1,8fe3a65e2ea6658d,5
16,0.069296,0.309758,0.921588,-0.068339,-0.229984,-0.065208,-2.043750,-36.525002,-6.600000,943.964355,85.940033,28098337,2,8fe3a65e2ea6658d,5
17,0.097478,0.320128,0.941352,-0.028939,0.005192,-0.047952,-1.968750,-37.181252,-6.262500,943.964355,85.940033,28098337,3,8fe3a65e2ea6658d,5
18,0.088084,0.358436,0.928298,-0.067422,0.013133,0.031000,-1.912500,-37.837502,-5.887500,943.964355,85.940033,28098337,0,8fe3a65e2ea6658d,5
19,0.078446,0.340380,0.959164,0.224105,-0.094605,-0.154010,-1.593750,-39.187500,-5.268750,943.964355,85.940033,28098337,1,8fe3a65e2ea6658d,5
20,0.136884,0.341600,0.925614,-0.026190,-0.034055,-0.022525,-1.331250,-39.487503,-5.118750,943.964355,85.940033,28098337,2,8fe3a65e2ea6658d,5
21,0.087230,0.350872,0.914390,0.055816,-0.153934,-0.005803,-1.237500,-39.806252,-5.006250,943.964355,85.940033,28098337,3,8fe3a65e2ea6658d,5
22,0.152622,0.382958,0.909998,0.001680,0.114076,0.021532,-1.162500,-40.162502,-4.762500,943.964355,85.940033,28098337,0,8fe3a65e2ea6658d,5
23,0.153720,0.361364,0.932080,-0.103691,-0.251135,-0.053678,-1.162500,-40.087502,-4.612500,943.964355,85.940033,28098337,1,8fe3a65e2ea6658d,5
24,0.151036,0.390156,0.883036,-0.007865,0.105295,-0.006108,-0.993750,-39.581253,-4.518750,943.964355,85.940033,28098337,2,8fe3a65e2ea6658d,5
25,0.156648,0.373808,0.880962,-0.048104,-0.065208,0.098117,-0.975000,-39.393753,-4.462500,943.964355,85.940033,28098337,3,8fe3a65e2ea6658d,5
26,0.183000,0.366366,0.912438,-0.020998,0.008094,-0.008934,-0.956250,-39.243752,-4.462500,943.964355,85.940033,28098337,4,8fe3a65e2ea6658d,5
27,0.423523,0.027664,0.781044,0.347954,0.720723,0.669565,-41.493752,-24.375002,-4.275000,943.964355,85.940033,28098408,0,8fe3a65e2ea6658d,5
28,0.416478,0.038857,0.869067,0.378725,1.377002,0.426982,-40.368752,-21.937500,-7.350000,943.964355,85.940033,28098408,1,8fe3a65e2ea6658d,5
29,0.129808,0.109068,0.750666,-0.258236,-0.025350,0.089107,-38.681252,-20.906250,-9.937500,943.964355,85.940033,28098408,2,8fe3a65e2ea6658d,5
30,0.382348,-0.071492,1.013759,-0.977814,-0.215171,-0.046501,-38.193752,-19.012501,-10.650001,943.964355,85.940033,28098408,3,8fe3a65e2ea6658d,5
31,-0.030408,-0.082167,0.377315,4.075115,7.557097,-1.309962,-34.650002,-20.137501,-11.850000,943.964355,85.940033,28098408,4,8fe3a65e2ea6658d,5
32,-1.334710,-0.355477,0.040046,-1.287513,0.446682,-3.188241,-27.637501,-22.893751,-9.918751,943.964355,85.940033,28098408,0,8fe3a65e2ea6658d,5
33,-1.295793,-0.061152,0.312747,-0.506927,-0.280455,-1.225436,-18.975000,-23.793751,-7.256250,943.964355,85.940033,28098408,1,8fe3a65e2ea6658d,5
34,-1.140792,-0.264405,-0.109526,0.699115,0.417896,0.110792,-11.868751,-22.875000,-6.225000,943.964355,85.940033,28098408,2,8fe3a65e2ea6658d,5
35,-0.882853,-0.644404,0.084607,-1.030423,-0.190508,1.012861,-0.225000,-25.312502,-1.762500,943.964355,85.940033,28098408,3,8fe3a65e2ea6658d,5
36,-0.818315,-0.272273,0.093879,0.284044,0.479286,-0.666358,26.550001,-29.643751,15.412500,943.964355,85.940033,28098408,4,8fe3a65e2ea6658d,5
37,-1.181479,-0.367281,-0.010126,1.708463,0.428815,-0.220745,36.056252,-24.768751,22.875000,943.964355,85.940033,28098408,0,8fe3a65e2ea6658d,5
38,-0.691984,-0.537562,-0.032299,-1.004844,0.122017,1.064630,42.431252,-20.100000,26.081251,943.964355,85.940033,28098408,1,8fe3a65e2ea6658d,5
39,-0.971059,-0.451461,0.205173,2.386657,1.738319,-1.136863,44.812500,-15.300000,27.075001,943.964355,85.940033,28098408,2,8fe3a65e2ea6658d,5

In [26]:
cantidad_nulos = df[['Bpressure', 'Lilluminance']].isnull().sum()
print(cantidad_nulos)

Bpressure       0
Lilluminance    0
dtype: int64

In [27]:
# Guardar los datos en un archivo CSV
df.to_csv('Dataset/HAR_TFM.csv', index=False)

In [28]:
# Agrupar por 'activity'
grouped = df.groupby('activity')

# Rellenar los valores nulos con la media entre el valor anterior y posterior
df[['counter']] = grouped[['counter']].apply(lambda x: x.interpolate().fillna(method='bfill'))

### Ajuste de columnas

In [29]:
# Contar la cantidad de ocurrencias de cada valor en la columna 'activity'
conteo_valores = df['activity'].value_counts()

# Imprimir el resultado
print(conteo_valores)

6    62608
3    61075
2    60570
1    55405
4    43687
5    26363
Name: activity, dtype: int64

In [30]:
# Eliminar las filas con los valores 3 y 6 en la columna 'activity'
#df = df.drop(df[(df['activity'] == 3) | (df['activity'] == 1)].index)
#df = df.drop(df[df['activity'] == 1].index)

In [31]:
df['activity'] = df['activity'].astype(int)
df['counter'] = df['counter'].astype(int)

#### Submuestreo y sobremuestreo de los valores

In [32]:
#import pandas as pd
#from sklearn.utils import resample

# Muestra la distribución actual de clases
#print(df['activity'].value_counts())

# Separar en diferentes DataFrames para cada clase
#df_classes = [df[df['activity'] == i] for i in df['activity'].unique()]

# Obtener la cantidad de datos de la clase mayoritaria
#max_samples = max([len(df_class) for df_class in df_classes])

# Realizar el submuestreo y sobremuestreo para cada clase
#df_balanced = []
#for df_class in df_classes:
#    df_class_upsampled = resample(df_class, replace=True, n_samples=max_samples, random_state=123)
#    df_balanced.append(df_class_upsampled)

# Combinar todos los DataFrames balanceados para formar el DataFrame final
#df = pd.concat(df_balanced)

In [33]:
# Contar la cantidad de ocurrencias de cada valor en la columna 'activity'
conteo_valores = df['activity'].value_counts()

# Imprimir el resultado
print(conteo_valores)

6    62608
3    61075
2    60570
1    55405
4    43687
5    26363
Name: activity, dtype: int64

In [34]:
df.head()

,Ax,Ay,Az,Gx,Gy,Gz,Mx,My,Mz,Bpressure,Lilluminance,timestamp,counter,deviceId,activity
0,-0.097234,0.418460,0.843996,0.286335,0.070782,0.084450,-1.36875,8.156250,-24.168751,943.964355,85.940033,28098336,0,8fe3a65e2ea6658d,5
1,0.249002,0.293410,1.201944,-0.177069,0.058947,0.357040,-1.44375,8.193750,-24.300001,943.964355,85.940033,28098336,1,8fe3a65e2ea6658d,5
2,0.240584,0.380152,1.015406,-0.172335,1.051955,0.423623,0.13125,8.212501,-23.943750,943.964355,85.940033,28098336,0,8fe3a65e2ea6658d,5
3,0.113704,0.335500,0.834236,-0.159355,0.307867,0.560376,1.83750,8.400001,-23.400002,943.964355,85.940033,28098336,1,8fe3a65e2ea6658d,5
4,0.038308,0.284992,0.928786,0.300766,0.246171,0.454623,3.61875,8.100000,-23.025002,943.964355,85.940033,28098336,2,8fe3a65e2ea6658d,5

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309708 entries, 0 to 309707
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Ax            309708 non-null  float64
 1   Ay            309708 non-null  float64
 2   Az            309708 non-null  float64
 3   Gx            309708 non-null  float64
 4   Gy            309708 non-null  float64
 5   Gz            309708 non-null  float64
 6   Mx            309708 non-null  float64
 7   My            309708 non-null  float64
 8   Mz            309708 non-null  float64
 9   Bpressure     309708 non-null  float64
 10  Lilluminance  309708 non-null  float64
 11  timestamp     309708 non-null  int64
 12  counter       309708 non-null  int64
 13  deviceId      309708 non-null  object
 14  activity      309708 non-null  int64
dtypes: float64(11), int64(3), object(1)
memory usage: 35.4+ MB

In [36]:
# Guardar el DataFrame como un archivo CSV
df.to_csv('Datos Preprocesados.csv', index=False)